######################
InputExcelPath       = "./test"
OutputProtoPath       = "./test"

#OutputDataCSharpPath = "./test/csharp/conf_data"
#OutputCodeCSharpPath = "./test/csharp/gen/conf"

# config for unity
OutputDataCSharpPath = "../ecunity/Assets/Resources/conf_data"
OutputCodeCSharpPath = "../ecunity/Assets/Scripts/gen/conf"

OutputDataGoPath     = "./test/go/conf_data"
OutputCodeGoPath     = "./test/go/gen/conf"

ProtoPackage = "Conf"
CSharpNamespace = "conf"
GoPackage       = "conf"
GoPackageFullPath   = "github.com/zero-yy/export-config-test/test/go/gen/conf"
